server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://db:5432/vehicle
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

resilience4j:
  retry:
    instances:
      f1:
        max-attempts: 2
        wait-duration: 250ms
      f2:
        max-attempts: 2
        wait-duration: 300ms
      f3:
        max-attempts: 1
        wait-duration: 200ms
  circuitbreaker:
    instances:
      f1:
        register-health-indicator: true
        sliding-window-size: 20
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
      f2:
        register-health-indicator: true
        sliding-window-size: 20
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
